language: "node_js"
node_js: "10"

before_script:
  - npm build-pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: iMega/grid-css-layout-editor
  target_branch: gh-pages
  on:
    branch: master
